const testData = {
  travelers: [
    {
      id: 1,
      name: "Ham Leadbeater",
      travelerType: "relaxer",
    },
    {
      id: 2,
      name: "Rachael Vaughten",
      travelerType: "thrill-seeker",
    },
    {
      id: 3,
      name: "Sibby Dawidowitsch",
      travelerType: "shopper",
    },
    {
      id: null,
      name: null,
      travelerType: null,
    },
  ],
  trips: [
    {
      id: 1,
      userID: 1,
      destinationID: 49,
      travelers: 1,
      date: "2022/09/16",
      duration: 8,
      status: "approved",
      suggestedActivities: [],
    },
    {
      id: 2,
      userID: 2,
      destinationID: 22,
      travelers: 5,
      date: "2022/10/04",
      duration: 18,
      status: "approved",
      suggestedActivities: [],
    },
    {
      id: 3,
      userID: 1,
      destinationID: 22,
      travelers: 4,
      date: "2021/05/22",
      duration: 17,
      status: "approved",
      suggestedActivities: [],
    },
    {
      id: 4,
      userID: 1,
      destinationID: 12,
      travelers: 2,
      date: "2023/09/28",
      duration: 5,
      status: "approved",
      suggestedActivities: [],
    },
    {
      id: 5,
      userID: 1,
      destinationID: 25,
      travelers: 7,
      date: "2022/09/12",
      duration: 1,
      status: "approved",
      suggestedActivities: [],
    },
    {
      id: 6,
      userID: 2,
      destinationID: 25,
      travelers: 7,
      date: "2023/10/11",
      duration: 1,
      status: "approved",
      suggestedActivities: [],
    },
    {
      id: 7,
      userID: 2,
      destinationID: 25,
      travelers: 7,
      date: "2022/10/02",
      duration: 5,
      status: "approved",
      suggestedActivities: [],
    },
  ],
  destinations: [
    {
      id: 49,
      destination: "Lima, Peru",
      estimatedLodgingCostPerDay: 70,
      estimatedFlightCostPerPerson: 400,
      image:
        "https://images.unsplash.com/photo-1489171084589-9b5031ebcf9b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2089&q=80",
      alt: "overview of city buildings with a clear sky",
    },
    {
      id: 25,
      destination: "Stockholm, Sweden",
      estimatedLodgingCostPerDay: 100,
      estimatedFlightCostPerPerson: 780,
      image:
        "https://images.unsplash.com/photo-1560089168-6516081f5bf1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80",
      alt: "city with boats on the water during the day time",
    },
    {
      id: 22,
      destination: "Sydney, Austrailia",
      estimatedLodgingCostPerDay: 130,
      estimatedFlightCostPerPerson: 950,
      image:
        "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80",
      alt: "opera house and city buildings on the water with boats",
    },
    {
      id: null,
      destination: null,
      estimatedLodgingCostPerDay: null,
      estimatedFlightCostPerPerson: null,
      image: null,
      alt: null,
    },
  ],
};

export default testData;
